// Comprehensive world currency list with approximate FX rates relative to USD.
// Rates are indicative and updated periodically. In production these would come from a live API.
export const CURRENCIES = [
  // Major reserve currencies
  { code: "USD", symbol: "$", label: "US Dollar", rate: 1 },
  { code: "EUR", symbol: "€", label: "Euro", rate: 0.92 },
  { code: "GBP", symbol: "£", label: "British Pound", rate: 0.79 },
  { code: "JPY", symbol: "¥", label: "Japanese Yen", rate: 149.5 },
  { code: "CHF", symbol: "Fr", label: "Swiss Franc", rate: 0.87 },
  { code: "CAD", symbol: "C$", label: "Canadian Dollar", rate: 1.36 },
  { code: "AUD", symbol: "A$", label: "Australian Dollar", rate: 1.52 },
  { code: "NZD", symbol: "NZ$", label: "New Zealand Dollar", rate: 1.64 },
  // Middle East
  { code: "AED", symbol: "د.إ", label: "UAE Dirham", rate: 3.67 },
  { code: "SAR", symbol: "﷼", label: "Saudi Riyal", rate: 3.75 },
  { code: "QAR", symbol: "﷼", label: "Qatari Riyal", rate: 3.64 },
  { code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar", rate: 0.31 },
  { code: "BHD", symbol: "د.ب", label: "Bahraini Dinar", rate: 0.38 },
  { code: "OMR", symbol: "﷼", label: "Omani Rial", rate: 0.39 },
  { code: "JOD", symbol: "د.ا", label: "Jordanian Dinar", rate: 0.71 },
  { code: "LBP", symbol: "ل.ل", label: "Lebanese Pound", rate: 89500 },
  { code: "ILS", symbol: "₪", label: "Israeli Shekel", rate: 3.67 },
  { code: "TRY", symbol: "₺", label: "Turkish Lira", rate: 34.2 },
  { code: "IRR", symbol: "﷼", label: "Iranian Rial", rate: 42000 },
  { code: "IQD", symbol: "ع.د", label: "Iraqi Dinar", rate: 1310 },
  // Asia
  { code: "CNY", symbol: "¥", label: "Chinese Yuan", rate: 7.24 },
  { code: "HKD", symbol: "HK$", label: "Hong Kong Dollar", rate: 7.82 },
  { code: "SGD", symbol: "S$", label: "Singapore Dollar", rate: 1.34 },
  { code: "INR", symbol: "₹", label: "Indian Rupee", rate: 83.3 },
  { code: "PKR", symbol: "₨", label: "Pakistani Rupee", rate: 278 },
  { code: "BDT", symbol: "৳", label: "Bangladeshi Taka", rate: 117 },
  { code: "LKR", symbol: "₨", label: "Sri Lankan Rupee", rate: 298 },
  { code: "NPR", symbol: "₨", label: "Nepalese Rupee", rate: 133 },
  { code: "MVR", symbol: "Rf", label: "Maldivian Rufiyaa", rate: 15.4 },
  { code: "THB", symbol: "฿", label: "Thai Baht", rate: 35.8 },
  { code: "IDR", symbol: "Rp", label: "Indonesian Rupiah", rate: 15800 },
  { code: "MYR", symbol: "RM", label: "Malaysian Ringgit", rate: 4.67 },
  { code: "PHP", symbol: "₱", label: "Philippine Peso", rate: 56.2 },
  { code: "VND", symbol: "₫", label: "Vietnamese Dong", rate: 24500 },
  { code: "KHR", symbol: "៛", label: "Cambodian Riel", rate: 4100 },
  { code: "LAK", symbol: "₭", label: "Lao Kip", rate: 21900 },
  { code: "MMK", symbol: "K", label: "Myanmar Kyat", rate: 2100 },
  { code: "KRW", symbol: "₩", label: "South Korean Won", rate: 1340 },
  { code: "TWD", symbol: "NT$", label: "Taiwan Dollar", rate: 31.8 },
  { code: "MNT", symbol: "₮", label: "Mongolian Tugrik", rate: 3400 },
  { code: "KZT", symbol: "₸", label: "Kazakhstani Tenge", rate: 475 },
  { code: "UZS", symbol: "so'm", label: "Uzbekistani Som", rate: 12700 },
  { code: "KGS", symbol: "с", label: "Kyrgyzstani Som", rate: 89.5 },
  { code: "TJS", symbol: "ЅМ", label: "Tajikistani Somoni", rate: 10.9 },
  { code: "TMT", symbol: "m", label: "Turkmenistani Manat", rate: 3.5 },
  { code: "AFN", symbol: "؋", label: "Afghan Afghani", rate: 71 },
  // Europe (non-Euro)
  { code: "NOK", symbol: "kr", label: "Norwegian Krone", rate: 10.8 },
  { code: "SEK", symbol: "kr", label: "Swedish Krona", rate: 10.5 },
  { code: "DKK", symbol: "kr", label: "Danish Krone", rate: 6.86 },
  { code: "ISK", symbol: "kr", label: "Icelandic Krona", rate: 139 },
  { code: "RUB", symbol: "₽", label: "Russian Ruble", rate: 92.5 },
  { code: "UAH", symbol: "₴", label: "Ukrainian Hryvnia", rate: 41.2 },
  { code: "PLN", symbol: "zł", label: "Polish Zloty", rate: 4.02 },
  { code: "CZK", symbol: "Kč", label: "Czech Koruna", rate: 23.2 },
  { code: "HUF", symbol: "Ft", label: "Hungarian Forint", rate: 360 },
  { code: "RON", symbol: "lei", label: "Romanian Leu", rate: 4.56 },
  { code: "BGN", symbol: "лв", label: "Bulgarian Lev", rate: 1.8 },
  { code: "HRK", symbol: "kn", label: "Croatian Kuna", rate: 6.95 },
  { code: "RSD", symbol: "дин", label: "Serbian Dinar", rate: 108 },
  { code: "MKD", symbol: "ден", label: "Macedonian Denar", rate: 57.5 },
  { code: "ALL", symbol: "L", label: "Albanian Lek", rate: 93.5 },
  { code: "BAM", symbol: "KM", label: "Bosnian Mark", rate: 1.8 },
  { code: "MDL", symbol: "L", label: "Moldovan Leu", rate: 17.8 },
  { code: "BYN", symbol: "Br", label: "Belarusian Ruble", rate: 3.27 },
  { code: "GEL", symbol: "₾", label: "Georgian Lari", rate: 2.72 },
  { code: "AMD", symbol: "֏", label: "Armenian Dram", rate: 388 },
  { code: "AZN", symbol: "₼", label: "Azerbaijani Manat", rate: 1.7 },
  // Americas
  { code: "MXN", symbol: "$", label: "Mexican Peso", rate: 17.2 },
  { code: "BRL", symbol: "R$", label: "Brazilian Real", rate: 5.05 },
  { code: "ARS", symbol: "$", label: "Argentine Peso", rate: 980 },
  { code: "CLP", symbol: "$", label: "Chilean Peso", rate: 905 },
  { code: "COP", symbol: "$", label: "Colombian Peso", rate: 4100 },
  { code: "PEN", symbol: "S/", label: "Peruvian Sol", rate: 3.75 },
  { code: "UYU", symbol: "$U", label: "Uruguayan Peso", rate: 39.5 },
  { code: "PYG", symbol: "₲", label: "Paraguayan Guarani", rate: 7350 },
  { code: "BOB", symbol: "Bs", label: "Bolivian Boliviano", rate: 6.9 },
  { code: "VES", symbol: "Bs", label: "Venezuelan Bolivar", rate: 36 },
  { code: "GTQ", symbol: "Q", label: "Guatemalan Quetzal", rate: 7.8 },
  { code: "HNL", symbol: "L", label: "Honduran Lempira", rate: 24.7 },
  { code: "NIO", symbol: "C$", label: "Nicaraguan Cordoba", rate: 36.8 },
  { code: "CRC", symbol: "₡", label: "Costa Rican Colon", rate: 520 },
  { code: "PAB", symbol: "B/.", label: "Panamanian Balboa", rate: 1 },
  { code: "DOP", symbol: "RD$", label: "Dominican Peso", rate: 58.5 },
  { code: "CUP", symbol: "$MN", label: "Cuban Peso", rate: 240 },
  { code: "JMD", symbol: "J$", label: "Jamaican Dollar", rate: 155 },
  { code: "TTD", symbol: "TT$", label: "Trinidad Dollar", rate: 6.78 },
  { code: "BBD", symbol: "Bds$", label: "Barbadian Dollar", rate: 2 },
  { code: "BSD", symbol: "B$", label: "Bahamian Dollar", rate: 1 },
  { code: "BZD", symbol: "BZ$", label: "Belize Dollar", rate: 2 },
  { code: "XCD", symbol: "EC$", label: "East Caribbean Dollar", rate: 2.7 },
  // Africa
  { code: "ZAR", symbol: "R", label: "South African Rand", rate: 18.5 },
  { code: "EGP", symbol: "£", label: "Egyptian Pound", rate: 48.6 },
  { code: "MAD", symbol: "د.م.", label: "Moroccan Dirham", rate: 9.95 },
  { code: "TND", symbol: "د.ت", label: "Tunisian Dinar", rate: 3.13 },
  { code: "DZD", symbol: "د.ج", label: "Algerian Dinar", rate: 134 },
  { code: "LYD", symbol: "ل.د", label: "Libyan Dinar", rate: 4.85 },
  { code: "SDG", symbol: "ج.س.", label: "Sudanese Pound", rate: 600 },
  { code: "ETB", symbol: "Br", label: "Ethiopian Birr", rate: 57.5 },
  { code: "KES", symbol: "KSh", label: "Kenyan Shilling", rate: 152 },
  { code: "UGX", symbol: "USh", label: "Ugandan Shilling", rate: 3780 },
  { code: "TZS", symbol: "TSh", label: "Tanzanian Shilling", rate: 2530 },
  { code: "RWF", symbol: "FRw", label: "Rwandan Franc", rate: 1280 },
  { code: "BIF", symbol: "FBu", label: "Burundian Franc", rate: 2860 },
  { code: "NGN", symbol: "₦", label: "Nigerian Naira", rate: 1580 },
  { code: "GHS", symbol: "₵", label: "Ghanaian Cedi", rate: 15.2 },
  { code: "SLL", symbol: "Le", label: "Sierra Leonean Leone", rate: 23000 },
  { code: "LRD", symbol: "L$", label: "Liberian Dollar", rate: 198 },
  { code: "GMD", symbol: "D", label: "Gambian Dalasi", rate: 67 },
  { code: "GNF", symbol: "FG", label: "Guinean Franc", rate: 8550 },
  { code: "XOF", symbol: "FCFA", label: "West African CFA Franc", rate: 600 },
  { code: "XAF", symbol: "FCFA", label: "Central African CFA Franc", rate: 600 },
  { code: "CDF", symbol: "FC", label: "Congolese Franc", rate: 2750 },
  { code: "AOA", symbol: "Kz", label: "Angolan Kwanza", rate: 825 },
  { code: "MZN", symbol: "MT", label: "Mozambican Metical", rate: 63.8 },
  { code: "ZMW", symbol: "ZK", label: "Zambian Kwacha", rate: 22.5 },
  { code: "ZWL", symbol: "Z$", label: "Zimbabwean Dollar", rate: 13.3 },
  { code: "BWP", symbol: "P", label: "Botswanan Pula", rate: 13.8 },
  { code: "NAD", symbol: "N$", label: "Namibian Dollar", rate: 18.5 },
  { code: "LSL", symbol: "L", label: "Lesotho Loti", rate: 18.5 },
  { code: "SZL", symbol: "E", label: "Eswatini Lilangeni", rate: 18.5 },
  { code: "MUR", symbol: "₨", label: "Mauritian Rupee", rate: 46.5 },
  { code: "SCR", symbol: "₨", label: "Seychellois Rupee", rate: 14.5 },
  { code: "MGA", symbol: "Ar", label: "Malagasy Ariary", rate: 4650 },
  { code: "DJF", symbol: "Fdj", label: "Djiboutian Franc", rate: 178 },
  { code: "SOS", symbol: "Sh", label: "Somali Shilling", rate: 571 },
  { code: "ERN", symbol: "Nfk", label: "Eritrean Nakfa", rate: 15 },
  { code: "STN", symbol: "Db", label: "Sao Tome Dobra", rate: 22.5 },
  { code: "GQE", symbol: "FK", label: "Equat. Guinean Ekwele", rate: 600 },
  // Oceania
  { code: "FJD", symbol: "FJ$", label: "Fijian Dollar", rate: 2.24 },
  { code: "PGK", symbol: "K", label: "Papua New Guinean Kina", rate: 3.7 },
  { code: "SBD", symbol: "SI$", label: "Solomon Islands Dollar", rate: 8.5 },
  { code: "VUV", symbol: "VT", label: "Vanuatu Vatu", rate: 119 },
  { code: "WST", symbol: "WS$", label: "Samoan Tala", rate: 2.7 },
  { code: "TOP", symbol: "T$", label: "Tongan Pa'anga", rate: 2.35 },
  { code: "XPF", symbol: "₣", label: "CFP Franc", rate: 110 },
];

export function convertFromUSD(usdAmount, currencyCode) {
  const c = CURRENCIES.find((x) => x.code === currencyCode) ?? CURRENCIES[0];
  return usdAmount * c.rate;
}

export function formatPrice(usdAmount, currencyCode) {
  const c = CURRENCIES.find((x) => x.code === currencyCode) ?? CURRENCIES[0];
  const value = convertFromUSD(usdAmount, currencyCode);
  // JPY, IDR, VND, KRW, etc. have no decimals
  const noDecimalCodes = ["JPY", "IDR", "VND", "KRW", "CLP", "UGX", "RWF", "BIF", "GNF", "CDF", "VUV", "XPF", "XAF", "XOF", "STN", "GQE", "KPW", "LAK", "KHR", "MMK", "PYG", "SLL", "UZS", "MGA", "MNT", "COP", "ISK"];
  if (noDecimalCodes.includes(c.code)) {
    const rounded = Math.round(value);
    return `${c.symbol}${rounded.toLocaleString("en-US")}`;
  }
  const rounded = Math.round(value);
  return `${c.symbol}${rounded.toLocaleString("en-US")}`;
}